version: "3"
services:

  nginx:
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend

  frontend:
    restart: unless-stopped
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    restart: unless-stopped
    build: ./backend
    ports:
      - "4000:4000"
