# Use the official Nginx base image
FROM nginx:latest

# Switch to the root user temporarily to perform necessary tasks
USER root

# Copy your custom Nginx configuration file to the container
COPY nginx.conf /etc/nginx/nginx.conf